### ISSUE TITLE
component can be used only with one Docker

### ISSUE THREAD

**Issue by ed-holland** [Sanderhuisman/home-assistant-custom-components#16]
My setup has several dockers runing on PI's.

Is it possible to extend it so that i can be used for more than one docker target? Maybe similar to how it can be done with Sensors.

My current workaround is to duplicate the component and changing the domain name.

**Comment by firestrife23** [comment]
Portainer does this by accessing docker's API via TCP protocol instead of traditional method of pointing at /var/run/docker.sock file. I would like to see something like this:

```
docker_monitor:
  servers:
    - host: 192.168.10.5:2375
      name: docker_1
    - host: 192.168.10.6:2375
      name: docker_2
    - host: 192.168.10.7:2375
      name: docker_3
```

P.S. This will make my life easier not having to re-add the volume /var/run/docker.sock to Hass.io container after upgrading.
