### ISSUE TITLE
All containers' properties are "UNKNOWN"

### ISSUE THREAD

**Issue by GuyKh** [Sanderhuisman/home-assistant-custom-components#19]
Using HA in a container with this configuration (in docker-compose):

```
  homeassistant:
    container_name: home-assistant
    restart: on-failure
    image: homeassistant/raspberrypi3-homeassistant:0.102.1
    volumes:
      - ${USERDIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8123:8123"
      - "6080:8080"
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: host
    labels:
     - "traefik.enable=false"
```

And here, in HA - the containers are loaded - but without data:
![image](https://user-images.githubusercontent.com/3136012/71557838-837f5100-2a54-11ea-8869-ae9bd3c5cd14.png)

What to do?
